In [1]:

import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('bike_sales_india.csv')

In [3]:
df.head()

,State,Avg Daily Distance (km),Brand,Model,Price (INR),Year of Manufacture,Engine Capacity (cc),Fuel Type,Mileage (km/l),Owner Type,Registration Year,Insurance Status,Seller Type,Resale Price (INR),City Tier
0,Karnataka,68.84,Royal Enfield,Hunter 350,252816,2021,672,Electric,78.41,Second,2024,Active,Individual,149934.18,Tier 3
1,Rajasthan,23.80,Bajaj,Dominar 400,131100,2020,769,Hybrid,89.98,Third,2023,Active,Individual,66960.30,Tier 3
2,Madhya Pradesh,27.67,KTM,125 Duke,201016,2020,216,Hybrid,71.46,Second,2023,Active,Dealer,141522.64,Tier 3
3,Karnataka,62.85,Kawasaki,Ninja 300,132482,2021,556,Petrol,51.73,Third,2021,Active,Dealer,56057.22,Tier 1
4,Madhya Pradesh,10.62,Yamaha,FZ V3,231796,2019,298,Petrol,54.72,Third,2019,Not Available,Individual,132538.36,Tier 3

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    10000 non-null  str
 1   Avg Daily Distance (km)  10000 non-null  float64
 2   Brand                    10000 non-null  str
 3   Model                    10000 non-null  str
 4   Price (INR)              10000 non-null  int64
 5   Year of Manufacture      10000 non-null  int64
 6   Engine Capacity (cc)     10000 non-null  int64
 7   Fuel Type                10000 non-null  str
 8   Mileage (km/l)           10000 non-null  float64
 9   Owner Type               10000 non-null  str
 10  Registration Year        10000 non-null  int64
 11  Insurance Status         10000 non-null  str
 12  Seller Type              10000 non-null  str
 13  Resale Price (INR)       10000 non-null  float64
 14  City Tier                10000 non-null  str
dtypes: float64(3), int64(4), str(8)
memory usage: 1.7 MB

In [5]:
df.isna().sum()

State                      0
Avg Daily Distance (km)    0
Brand                      0
Model                      0
Price (INR)                0
Year of Manufacture        0
Engine Capacity (cc)       0
Fuel Type                  0
Mileage (km/l)             0
Owner Type                 0
Registration Year          0
Insurance Status           0
Seller Type                0
Resale Price (INR)         0
City Tier                  0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:

df.rename(columns={"Price (INR)":'Price'},inplace=True)
df.head()

,State,Avg Daily Distance (km),Brand,Model,Price,Year of Manufacture,Engine Capacity (cc),Fuel Type,Mileage (km/l),Owner Type,Registration Year,Insurance Status,Seller Type,Resale Price (INR),City Tier
0,Karnataka,68.84,Royal Enfield,Hunter 350,252816,2021,672,Electric,78.41,Second,2024,Active,Individual,149934.18,Tier 3
1,Rajasthan,23.80,Bajaj,Dominar 400,131100,2020,769,Hybrid,89.98,Third,2023,Active,Individual,66960.30,Tier 3
2,Madhya Pradesh,27.67,KTM,125 Duke,201016,2020,216,Hybrid,71.46,Second,2023,Active,Dealer,141522.64,Tier 3
3,Karnataka,62.85,Kawasaki,Ninja 300,132482,2021,556,Petrol,51.73,Third,2021,Active,Dealer,56057.22,Tier 1
4,Madhya Pradesh,10.62,Yamaha,FZ V3,231796,2019,298,Petrol,54.72,Third,2019,Not Available,Individual,132538.36,Tier 3

In [8]:
df.drop(columns=['Seller Type'],inplace=True)

In [9]:
df.drop(columns=['City Tier'],inplace=True)
df

,State,Avg Daily Distance (km),Brand,Model,Price,Year of Manufacture,Engine Capacity (cc),Fuel Type,Mileage (km/l),Owner Type,Registration Year,Insurance Status,Resale Price (INR)
0,Karnataka,68.84,Royal Enfield,Hunter 350,252816,2021,672,Electric,78.41,Second,2024,Active,149934.18
1,Rajasthan,23.80,Bajaj,Dominar 400,131100,2020,769,Hybrid,89.98,Third,2023,Active,66960.30
2,Madhya Pradesh,27.67,KTM,125 Duke,201016,2020,216,Hybrid,71.46,Second,2023,Active,141522.64
3,Karnataka,62.85,Kawasaki,Ninja 300,132482,2021,556,Petrol,51.73,Third,2021,Active,56057.22
4,Madhya Pradesh,10.62,Yamaha,FZ V3,231796,2019,298,Petrol,54.72,Third,2019,Not Available,132538.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Gujarat,67.72,Hero,Passion Pro,95040,2024,297,Electric,88.03,Third,2024,Not Available,62025.20
9996,Delhi,19.94,Bajaj,CT 100,110369,2015,210,Hybrid,74.89,Third,2020,Active,80378.40
9997,West Bengal,79.95,Bajaj,Pulsar 150,313806,2018,267,Hybrid,76.78,First,2018,Expired,199506.70
9998,Madhya Pradesh,16.07,Honda,Dio,204068,2018,856,Electric,97.75,Second,2021,Active,130978.70
9999,West Bengal,51.16,Royal Enfield,Classic 350,323583,2018,529,Petrol,41.68,Second,2018,Expired,142139.85

In [10]:
df.shape

(10000, 13)

In [11]:
df.columns

Index(['State', 'Avg Daily Distance (km)', 'Brand', 'Model', 'Price',
       'Year of Manufacture', 'Engine Capacity (cc)', 'Fuel Type',
       'Mileage (km/l)', 'Owner Type', 'Registration Year', 'Insurance Status',
       'Resale Price (INR)'],
      dtype='str')

In [12]:
# brand= df['Brand'].value_counts().reset_index()
# brand.columns= ['Brand','Count']

# fig=px.bar( 
#     brand,
#     x='Brand',
#     y='Count',
#     title='Number of bikes by brand'
#     )
# fig.update_layout(title_x=0.5)
# fig.show()

In [14]:
brand_count = df['Brand'].value_counts().reset_index()
brand_count.columns = ['Brand', 'Count']

fig = px.bar(
    brand_count,
    x='Brand',
    y='Count',
    color='Count',
    title='Bike Count by Brand'
)

fig.show()

In [ ]:
state_price = df.groupby('State', as_index=False)['Price'].mean()

fig = px.bar(
    state_price,
    x='State',
    y='Price',
    color='Price',
    title='Average Bike Price by State'
)

fig.show()

In [ ]:
fig=px.pie(
    df,
    names='Fuel Type',
    title='Fuel Type Distribution',
    hole=0.3,
    
    color_discrete_sequence=px.colors.qualitative.Set3
)

fig.update_layout(title_x=0.5)
fig.show()

In [ ]:

# data = {
#     "City": ["Delhi", "Mumbai", "Bengaluru", "Chennai", "Kolkata"],
#     "Latitude": [28.6139, 19.0760, 12.9716, 13.0827, 22.5726],
#     "Longitude": [77.2090, 72.8777, 77.5946, 80.2707, 88.3639],
#     "Sales": [500, 700, 600, 400, 300]
# }

# df = pd.DataFrame(data)
# df

In [ ]:
fig = px.density_heatmap(
    df,
    x="Price",
    y="Mileage (km/l)",
    color_continuous_scale="Viridis"
)
fig.update_layout(
    title='heatmap'
)
fig.show()

In [37]:
fig = px.density_heatmap(
    df,
    x='Engine Capacity (cc)',
    y='Mileage (km/l)',
    color_continuous_scale='Plasma',
    title='Engine Capacity vs Mileage Density'
)

fig.update_layout(title_x=0.5)

fig.show()

In [ ]:
# avg price by brand

brand_price = df.groupby("Brand")["Price"].mean().reset_index()

fig= px.bar(brand_price,
       x="Brand",
       y="Price",
       color="Price",
     title= 'Average price by Brand',

    )
fig.show()

In [ ]:
data = df.groupby(['Brand','Model'])[['Price','Resale Price (INR)']].mean().reset_index()
fig = px.scatter(
    data,
    x="Price",
    y="Resale Price (INR)",
    hover_data=["Model"],
    color="Brand",  #Model

    color_discrete_sequence=px.colors.qualitative.Dark24
)

fig.update_layout(
    template="plotly_dark",
    title="Price vs Resale Price",
    title_x=0.5
)

fig.show()

In [ ]:
# fig=px.scatter(
#     df,
#     x="Mileage (km/l)",
#     y="Price",
# )
# fig.show()

In [ ]:
fig = px.scatter(
    df,
    x='Mileage (km/l)',
    y='Price',
    color='Fuel Type',
    hover_data=['Brand', 'Model'],
    title='Mileage vs Price'
)
fig.update_layout(
    title_x=0.5,
    template='ggplot2'
)
fig.show()

In [30]:
fig = px.scatter(
    df,
    x='Mileage (km/l)',
    y='Price',
    size='Engine Capacity (cc)',
    color='Fuel Type',
    hover_name='Brand',
    hover_data=['Model'],
    title='Mileage vs Price Bubble Chart',
    template='plotly_dark'
)

fig.update_layout(title_x=0.5)

fig.show()

In [31]:
reg = df.groupby('Registration Year').size().reset_index(name='Count')

fig = px.bar(
    reg,
    x='Registration Year',
    y='Count',
    color='Count',
    title='Bike Registration by Year'
)
fig.update_layout(
    title_x=0.5,
    template='plotly_dark'
)

fig.show()

In [ ]:
# reg= df.groupby('Registration Year').size().reset_index(name='Count')
# fig=px.bar(
#     reg,
#     x='Registration Year',
#     y='Count',
#     title='Registration count by year',
#     color='Count',
# )
# fig.update_layout(
#     title_x=0.5,
#     template='plotly_dark'
# )
# fig.show()

In [ ]:
fig=df.head(50)

In [ ]:

fig = px.treemap(
    df,
    path=['Brand', 'Model'],
    title='Brand and Model Distribution'
)
fig.update_layout(
    title="<b>Brand and Model Distribution</b>",
    title_x=0.5
    )
fig.show()

In [34]:
fig = px.treemap(
    df,
    path=['Brand','Model'],
    values='Price',
    color='Price',
    color_continuous_scale='Viridis',
    title='Brand and Model Wise Bike Prices'
)

fig.update_layout(
    title_x=0.5,
    template='plotly_dark'
)

fig.show()

In [ ]:

model_count=df['Model'].value_counts().reset_index()
model_count.columns=['Model','Count']

fig=px.bar(
    model_count,
    x="Model",
    y="Count",
    title='<b>average price by brand</b>',
)
fig.update_layout(
    #template="plotly_dark",
    title_x=0.5,
    title={
        'text': "<b><span style='color:#00E5FF;'>Average price by Model</span></b>",
        'x': 0.5,
        'xanchor': 'center',
        'font': dict(size=30, family='Arial Black')
    },
    
)

fig.show()

In [ ]:
# fig.update_layout(
#     title={
#         'text': "<b>🚲 BIKE SALES INDIA</b><br><sup>Model-wise Bike Count Analysis</sup>",
#         'x': 0.5,
#         'xanchor': 'center',
#         'font': dict(size=28, family='Verdana', color='cyan')
#     },
#     template='plotly_dark'
# )

In [ ]:
#3

avg_resale= (df.groupby('Brand')['Resale Price (INR)'].mean().reset_index().sort_values(by="Resale Price (INR)", ascending=False))
fig= px.bar(
    avg_resale,
    x='Brand',
    y='Resale Price (INR)',
    color='Brand'
)
fig.update_layout(
    title='<b>Average Resale Price by Brand</b>',
    title_x=0.5
)

fig.show()

In [ ]:
# Top 5 brands
top_brands = df['Brand'].value_counts().head(15).index

filtered_df = df[df['Brand'].isin(top_brands)]

fig = px.box(
    filtered_df,
    x='Model',
    y='Resale Price (INR)',
    color='Brand',
    title='Brand vs Model Price Comparison',
    points='outliers'
)

fig.show()

In [54]:

# Top 10 models with the most listings (optional)
top_models = (
    df['Model']
    .value_counts()
    .head(15)
    .index
)

# Filter dataset
filtered_df = df[df['Model'].isin(top_models)]

# Create Box Plot
fig = px.box(
    filtered_df,
    x='Model',
    y='Resale Price (INR)',
    color='Brand',
    title='<b>Brand vs Model Price Comparison</b>',
    points='outliers'   # Show outliers
)

fig.update_layout(
    xaxis_title='Model',
    yaxis_title='Resale Price (INR)',
    template='plotly_white',
    title_x=0.5,
    title_font_size=24,
    font=dict(size=14),
)

fig.show()

In [51]:
fig = px.area(
    year_price,
    x='Year of Manufacture',
    y='Price',
    title='Average Price Area Trend'
)
fig.update_layout(
    title_x=0.5,
    template='plotly_dark',
    title_font_size=24,
    font=dict(size=14),
)

fig.show()

In [55]:
fig = px.histogram(
    df,
    x='Price',
    nbins=30,
    color='Fuel Type',
    title='<b>Bike Price Distribution</b>',
    
)
fig.update_layout(
    template='plotly_dark',
        title_x=0.5,
        title_font_size=24,
    font=dict(size=14),

)
fig.show()

In [56]:
year_price = df.groupby('Year of Manufacture')['Price'].mean().reset_index()

fig = px.line(
    year_price,
    x='Year of Manufacture',
    y='Price',
    markers=True,
    title='<b>Average Bike Price Trend Over Manufacturing Years</b>',
    template='plotly_dark'
)

fig.update_traces(line_width=4)

fig.update_layout(
    title_x=0.5,
    xaxis_title='Manufacturing Year',
    yaxis_title='Average Price',
    title_font_size=24,
    font=dict(size=14),
)

fig.show()

In [58]:
fig = px.box(
    df,
    x='Brand',
    y='Price',
    color='Brand',
    title='<b><u>Price Distribution by Brand</b></u>',
    template='plotly_dark'
)

fig.update_layout(title_x=0.5)

fig.show()

In [61]:
fig = px.violin(
    df,
    x='Fuel Type',
    y='Mileage (km/l)',
    color='Fuel Type',
    box=True,
    points='all',
    title='<b><u>Mileage Distribution by Fuel Type</b></u>',
    template='plotly_dark'
)

fig.update_layout(title_x=0.5,
                  title_font_size=24,
    font=dict(size=14),)
# textposition='outside'


fig.show()

In [35]:
fig = px.sunburst(
    df,
    path=['Brand','Model','Fuel Type'],
    values='Price',
    color='Price',
    color_continuous_scale='Turbo',
    title='Brand → Model → Fuel Type'
)

fig.update_layout(title_x=0.5)

fig.show()

In [38]:
fig = px.scatter_matrix(
    df,
    dimensions=[
        'Price',
        'Mileage (km/l)',
        'Engine Capacity (cc)',
        'Resale Price (INR)'
    ],
    color='Fuel Type',
    template='plotly_dark'
)

fig.update_layout(title='Scatter Matrix', title_x=0.5)

fig.show()

In [39]:
fig = px.parallel_coordinates(
    df,
    dimensions=[
        'Price',
        'Mileage (km/l)',
        'Engine Capacity (cc)',
        'Resale Price (INR)'
    ],
    color='Price',
    color_continuous_scale=px.colors.sequential.Viridis
)

fig.update_layout(title='Parallel Coordinates', title_x=0.5)

fig.show()

In [62]:
insurance = df['Insurance Status'].value_counts().reset_index()
insurance.columns = ['Insurance Status', 'Count']

fig = px.funnel(
    insurance,
    x='Count',
    y='Insurance Status',
    color='Insurance Status',
    title='Insurance Status Funnel'
)

fig.show()

In [63]:
insurance = df['Insurance Status'].value_counts().reset_index()
insurance.columns = ['Insurance Status', 'Count']

fig = px.bar(
    insurance,
    x='Insurance Status',
    y='Count',
    color='Insurance Status',
    text='Count',
    title='Insurance Status Distribution',
    template='plotly_dark'
)

fig.update_traces(textposition='outside')

fig.show()

In [64]:
fig = px.sunburst(
    df,
    path=['Insurance Status', 'Fuel Type'],
    values='Price',
    title='Insurance Status by Fuel Type'
)

fig.show()

In [65]:
fig = px.treemap(
    df,
    path=['Owner Type', 'Brand'],
    values='Price',
    color='Price',
    color_continuous_scale='Viridis',
    title='Owner Type by Brand'
)

fig.show()

In [66]:
fig = px.violin(
    df,
    x='Owner Type',
    y='Price',
    color='Owner Type',
    box=True,
    points='all',
    title='Price Distribution by Owner Type'
)

fig.show()

In [67]:
owner = df['Owner Type'].value_counts().reset_index()
owner.columns = ['Owner Type', 'Count']

fig = px.bar(
    owner,
    x='Owner Type',
    y='Count',
    color='Owner Type',
    text='Count',
    title='Owner Type Distribution',
    template='plotly_dark'
)

fig.update_traces(textposition='outside')

fig.show()